= nb2l
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en

image:https://img.shields.io/pypi/v/nb2l.svg["PyPI", link="https://pypi.org/project/nb2l/"]
image:https://github.com/flashcode/nb2l/workflows/Tests/badge.svg["Tests", link="https://github.com/flashcode/nb2l/actions"]

Nb2l is a Python script to convert numbers to literal French text.

Numbers from `-999 999 999 999 999 999 999` to `999 999 999 999 999 999 999`
are accepted.

The script just requires Python >= 3.6.

== Examples

From Python:

[source,python]
----
>>> from nb2l import nb2l
>>> nb2l(123456)
'cent vingt-trois mille quatre cent cinquante-six'
----

From command line:

----
$ nb2l 0 -15 123456 6824718
zéro
moins quinze
cent vingt-trois mille quatre cent cinquante-six
six millions huit cent vingt-quatre mille sept cent dix-huit
----

== Copyright

Copyright (C) 2012-2020 Sébastien Helleu <flashcode@flashtux.org>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
